### ISSUE TITLE
AR demo crash with the following

### ISSUE THREAD

**Issue by wangjiangchuan** [googlevr/poly-sample-android#1]
Process: com.google.ar.core.examples.java.helloar, PID: 18947
                                                                                          java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                                                              at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                                                              at com.google.ar.core.examples.java.helloar.HelloArActivity.onCreate(HelloArActivity.java:119)
                                                                                              at android.app.Activity.performCreate(Activity.java:6975)
                                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                              at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Following the instructions in the README.md, I had successfully run the PolySample demo in Google Pixel XL. However, the guidence for AR demo failed to lunch. The above is the logs.

**Comment by btco** [comment]
This sample is a fork of the Google ARCore SDK sample and it looks like the error is happening in the original ARCore sample code rather than the Poly-specific implementation. Can you test the ARCore sample from https://github.com/google-ar/arcore-android-sdk to see if you get the same error?

**Comment by btco** [comment]
Closing this for now. Please reopen if you find that the ARCore sample isn't crashing but PolySampleARCore is.
